<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>Femur.Chtml</PackageId>
    <Authors>Nicholas Quandt</Authors>
    <Company>Quandt</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <OutputType>Library</OutputType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../Parsing/src/Femur.Parsing.csproj" />
    <ProjectReference Include="../../../Markup.Abstractions/src/Femur.Markup.Abstractions.csproj" />
    <ProjectReference Include="../../../Html/Parser/src/Femur.Html.Parser.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

</Project>

