<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>Femur.Hosting.Web</PackageId>	  
	  <Authors>Nicholas Quandt</Authors>
	  <Company>Quandt</Company>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <OutputType>Library</OutputType>

    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <!-- <FrameworkReference Include="Microsoft.AspNetCore.App" /> -->
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Femur.Hosting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>