<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>Femur</PackageId>	  
	  <Authors>Nicholas Quandt</Authors>
	  <Company>Quandt</Company>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <OutputType>Library</OutputType>

    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>    
    <ProjectReference Include="..\FileSystem\src\Femur.FileSystem.csproj" />
    <ProjectReference Include="..\Serialization\src\Femur.Serialization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>


</Project>
