using System.Text;

namespace ChtmlCompiler;

/// <summary>
/// Generates code for the TemplateFunctions helper class.
/// </summary>
public static class TemplateFunctionsGenerator
{
    /// <summary>
    /// Generates the TemplateFunctions class code.
    /// </summary>
    public static string Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("using System.IO;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using Markdig;");
        sb.AppendLine("using Markdig.Extensions.Yaml;");
        sb.AppendLine("using Markdig.Syntax;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using YamlDotNet.RepresentationModel;");
        sb.AppendLine("using Shared.Meta;");
        sb.AppendLine();
        sb.AppendLine("namespace Templates.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Helper functions for template variable generation.");
        sb.AppendLine("/// These functions can be called from vars in front matter using function::MethodName() syntax.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class TemplateFunctions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Loads markdown content from a file relative to the output directory.");
        sb.AppendLine("    /// The file path should be relative to the templates root directory.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"filePath\">Relative path to the markdown file (e.g., \"./home.md\" or \"pages/about/en.md\")</param>");
        sb.AppendLine("    /// <param name=\"globalProps\">Global props for context</param>");
        sb.AppendLine("    /// <returns>A RenderPipe that renders the markdown content as HTML</returns>");
        sb.AppendLine("    public static RenderPipe<GlobalProps> LoadMarkdown(string filePath, GlobalProps globalProps)");
        sb.AppendLine("    {");
        sb.AppendLine("        // Normalize the file path (remove ./ prefix if present)");
        sb.AppendLine("        var normalizedPath = filePath.TrimStart('.').TrimStart('/').Replace('/', Path.DirectorySeparatorChar);");
        sb.AppendLine("        ");
        sb.AppendLine("        // Build path relative to output directory (where markdown files are copied)");
        sb.AppendLine("        var baseDir = AppContext.BaseDirectory;");
        sb.AppendLine("        var fullPath = Path.Combine(baseDir, normalizedPath);");
        sb.AppendLine("        ");
        sb.AppendLine("        // Fallback: try with original path structure");
        sb.AppendLine("        if (!File.Exists(fullPath))");
        sb.AppendLine("        {");
        sb.AppendLine("            fullPath = Path.Combine(baseDir, filePath.TrimStart('.').TrimStart('/'));");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        if (!File.Exists(fullPath))");
        sb.AppendLine("        {");
        sb.AppendLine("            return new RenderPipe<GlobalProps>(async ctx =>");
        sb.AppendLine("            {");
        sb.AppendLine("                await ctx.Writer.WriteAsync($\"<!-- Error: Markdown file not found: {filePath} -->\");");
        sb.AppendLine("            });");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        var markdownContent = File.ReadAllText(fullPath);");
        sb.AppendLine("        ");
        sb.AppendLine("        // Process markdown with Markdig");
        sb.AppendLine("        var pipeline = new MarkdownPipelineBuilder()");
        sb.AppendLine("            .UseYamlFrontMatter()");
        sb.AppendLine("            .UseAdvancedExtensions()");
        sb.AppendLine("            .Build();");
        sb.AppendLine("        ");
        sb.AppendLine("        // Parse and render markdown to HTML (front matter is automatically excluded)");
        sb.AppendLine("        var document = Markdig.Markdown.Parse(markdownContent, pipeline);");
        sb.AppendLine("        var htmlContent = document.ToHtml(pipeline);");
        sb.AppendLine("        ");
        sb.AppendLine("        return new RenderPipe<GlobalProps>(async ctx =>");
        sb.AppendLine("        {");
        sb.AppendLine("            await ctx.Writer.WriteAsync(htmlContent);");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Loads markdown content from a file and returns an instance of TProps.");
        sb.AppendLine("    /// Front matter fields become props, and Body is set as a RenderPipe.");
        sb.AppendLine("    /// Supports fallback file paths (tries first path, then fallback if not found).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <typeparam name=\"TProps\">The props type (e.g., ContentProps) with front matter fields and Body RenderPipe property</typeparam>");
        sb.AppendLine("    /// <param name=\"filePath\">Primary file path (supports {globalProps.X} interpolation)</param>");
        sb.AppendLine("    /// <param name=\"fallbackPath\">Optional fallback file path if primary is not found</param>");
        sb.AppendLine("    /// <param name=\"globalProps\">Global props for context and path interpolation</param>");
        sb.AppendLine("    /// <returns>An instance of TProps with front matter fields and Body RenderPipe</returns>");
        sb.AppendLine("    public static TProps LoadMarkdown<TProps>(string filePath, string? fallbackPath, GlobalProps globalProps) where TProps : class");
        sb.AppendLine("    {");
        sb.AppendLine("        // Interpolate {globalProps.X} in file path");
        sb.AppendLine("        var interpolatedPath = InterpolatePath(filePath, globalProps);");
        sb.AppendLine("        var interpolatedFallback = fallbackPath != null ? InterpolatePath(fallbackPath, globalProps) : null;");
        sb.AppendLine("        ");
        sb.AppendLine("        // Normalize paths");
        sb.AppendLine("        var normalizedPath = interpolatedPath.TrimStart('.').TrimStart('/').Replace('/', Path.DirectorySeparatorChar);");
        sb.AppendLine("        var normalizedFallback = interpolatedFallback?.TrimStart('.').TrimStart('/').Replace('/', Path.DirectorySeparatorChar);");
        sb.AppendLine("        ");
        sb.AppendLine("        var baseDir = AppContext.BaseDirectory;");
        sb.AppendLine("        var fullPath = Path.Combine(baseDir, normalizedPath);");
        sb.AppendLine("        ");
        sb.AppendLine("        // Try fallback if primary doesn't exist");
        sb.AppendLine("        if (!File.Exists(fullPath) && normalizedFallback != null)");
        sb.AppendLine("        {");
        sb.AppendLine("            fullPath = Path.Combine(baseDir, normalizedFallback);");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        if (!File.Exists(fullPath))");
        sb.AppendLine("        {");
        sb.AppendLine("            throw new FileNotFoundException($\"Markdown file not found: {interpolatedPath}\" + (normalizedFallback != null ? $\" or {interpolatedFallback}\" : \"\"));");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        var markdownContent = File.ReadAllText(fullPath);");
        sb.AppendLine("        ");
        sb.AppendLine("        // Process markdown with Markdig");
        sb.AppendLine("        var pipeline = new MarkdownPipelineBuilder()");
        sb.AppendLine("            .UseYamlFrontMatter()");
        sb.AppendLine("            .UseAdvancedExtensions()");
        sb.AppendLine("            .Build();");
        sb.AppendLine("        ");
        sb.AppendLine("        var document = Markdig.Markdown.Parse(markdownContent, pipeline);");
        sb.AppendLine("        ");
        sb.AppendLine("        // Extract front matter");
        sb.AppendLine("        var frontMatter = ExtractFrontMatter(document);");
        sb.AppendLine("        ");
        sb.AppendLine("        // Extract markdown body");
        sb.AppendLine("        var markdownBody = ExtractMarkdownBody(markdownContent);");
        sb.AppendLine("        ");
        sb.AppendLine("        // Convert markdown body to HTML");
        sb.AppendLine("        var htmlContent = document.ToHtml(pipeline);");
        sb.AppendLine("        ");
        sb.AppendLine("        // Create props instance");
        sb.AppendLine("        var props = CreatePropsFromFrontMatter<TProps>(frontMatter ?? new Dictionary<string, object>(), markdownBody);");
        sb.AppendLine("        ");
        sb.AppendLine("        // Set Body as RenderPipe");
        sb.AppendLine("        var bodyProp = typeof(TProps).GetProperty(\"Body\");");
        sb.AppendLine("        if (bodyProp != null && bodyProp.PropertyType.IsAssignableFrom(typeof(RenderPipe<GlobalProps>)))");
        sb.AppendLine("        {");
        sb.AppendLine("            var bodyRenderPipe = new RenderPipe<GlobalProps>(async ctx =>");
        sb.AppendLine("            {");
        sb.AppendLine("                await ctx.Writer.WriteAsync(htmlContent);");
        sb.AppendLine("            });");
        sb.AppendLine("            bodyProp.SetValue(props, bodyRenderPipe);");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        return props;");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Interpolates {globalProps.X} placeholders in a file path.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private static string InterpolatePath(string path, GlobalProps globalProps)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrEmpty(path)) return path;");
        sb.AppendLine("        ");
        sb.AppendLine("        var result = path;");
        sb.AppendLine("        var propsType = typeof(GlobalProps);");
        sb.AppendLine("        ");
        sb.AppendLine("        // Find all {globalProps.X} patterns");
        sb.AppendLine("        var pattern = new System.Text.RegularExpressions.Regex(@\"\\{globalProps\\.([^}]+)\\}\");");
        sb.AppendLine("        result = pattern.Replace(result, match =>");
        sb.AppendLine("        {");
        sb.AppendLine("            var propName = match.Groups[1].Value;");
        sb.AppendLine("            var prop = propsType.GetProperty(propName);");
        sb.AppendLine("            if (prop != null)");
        sb.AppendLine("            {");
        sb.AppendLine("                var value = prop.GetValue(globalProps);");
        sb.AppendLine("                return value?.ToString() ?? \"\";");
        sb.AppendLine("            }");
        sb.AppendLine("            return match.Value; // Return original if property not found");
        sb.AppendLine("        });");
        sb.AppendLine("        ");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Loads a collection of markdown files matching a pattern and returns them as props objects.");
        sb.AppendLine("    /// Each file's YAML front matter is parsed and passed as props to the component.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <typeparam name=\"TProps\">The input props type for the component (e.g., Components.Experience.IndexInputProps)</typeparam>");
        sb.AppendLine("    /// <param name=\"pattern\">File pattern to match (e.g., \"./pages/experience/*.md\")</param>");
        sb.AppendLine("    /// <param name=\"globalProps\">Global props for context</param>");
        sb.AppendLine("    /// <returns>An IEnumerable of props objects, sorted by start date (descending)</returns>");
        sb.AppendLine("    public static IEnumerable<TProps> LoadAsCollection<TProps>(string pattern, GlobalProps globalProps) where TProps : class");
        sb.AppendLine("    {");
        sb.AppendLine("        // Normalize pattern and find matching files");
        sb.AppendLine("        var normalizedPattern = pattern.TrimStart('.').TrimStart('/').Replace('/', Path.DirectorySeparatorChar);");
        sb.AppendLine("        var baseDir = AppContext.BaseDirectory;");
        sb.AppendLine("        ");
        sb.AppendLine("        // Convert glob pattern to directory and file pattern");
        sb.AppendLine("        var lastSlash = normalizedPattern.LastIndexOf(Path.DirectorySeparatorChar);");
        sb.AppendLine("        string searchDir;");
        sb.AppendLine("        string filePattern;");
        sb.AppendLine("        ");
        sb.AppendLine("        if (lastSlash >= 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            searchDir = Path.Combine(baseDir, normalizedPattern.Substring(0, lastSlash));");
        sb.AppendLine("            filePattern = normalizedPattern.Substring(lastSlash + 1);");
        sb.AppendLine("        }");
        sb.AppendLine("        else");
        sb.AppendLine("        {");
        sb.AppendLine("            searchDir = baseDir;");
        sb.AppendLine("            filePattern = normalizedPattern;");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        if (!Directory.Exists(searchDir))");
        sb.AppendLine("        {");
        sb.AppendLine("            yield break;");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        // Find matching files");
        sb.AppendLine("        var files = Directory.GetFiles(searchDir, filePattern, SearchOption.TopDirectoryOnly);");
        sb.AppendLine("        ");
        sb.AppendLine("        // Process markdown pipeline");
        sb.AppendLine("        var pipeline = new MarkdownPipelineBuilder()");
        sb.AppendLine("            .UseYamlFrontMatter()");
        sb.AppendLine("            .UseAdvancedExtensions()");
        sb.AppendLine("            .Build();");
        sb.AppendLine("        ");
        sb.AppendLine("        // Parse each file and collect data");
        sb.AppendLine("        var items = new List<(Dictionary<string, object> frontMatter, string markdownBody, DateTime? startDate)>();");
        sb.AppendLine("        ");
        sb.AppendLine("        foreach (var filePath in files)");
        sb.AppendLine("        {");
        sb.AppendLine("            var markdownContent = File.ReadAllText(filePath);");
        sb.AppendLine("            var document = Markdig.Markdown.Parse(markdownContent, pipeline);");
        sb.AppendLine("            ");
        sb.AppendLine("            // Extract front matter");
        sb.AppendLine("            var frontMatter = ExtractFrontMatter(document);");
        sb.AppendLine("            if (frontMatter == null) continue;");
        sb.AppendLine("            ");
        sb.AppendLine("            // Extract markdown body (everything after front matter)");
        sb.AppendLine("            var markdownBody = ExtractMarkdownBody(markdownContent);");
        sb.AppendLine("            ");
        sb.AppendLine("            // Try to parse start date for sorting");
        sb.AppendLine("            DateTime? startDate = null;");
        sb.AppendLine("            if (frontMatter.TryGetValue(\"start\", out var startObj) && startObj != null)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (DateTime.TryParse(startObj.ToString(), out var parsedDate))");
        sb.AppendLine("                {");
        sb.AppendLine("                    startDate = parsedDate;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            ");
        sb.AppendLine("            items.Add((frontMatter, markdownBody, startDate));");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        // Sort by start date (descending, most recent first)");
        sb.AppendLine("        items = items.OrderByDescending(i => i.startDate ?? DateTime.MinValue).ToList();");
        sb.AppendLine("        ");
        sb.AppendLine("        // Yield each props object");
        sb.AppendLine("        foreach (var (frontMatter, markdownBody, _) in items)");
        sb.AppendLine("        {");
        sb.AppendLine("            yield return CreatePropsFromFrontMatter<TProps>(frontMatter, markdownBody);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Infers the component type from a props type name.");
        sb.AppendLine("    /// Pattern: Components.{Category}.{Component}.{PropsType} -> Components.{Category}.{Component}.Index");
        sb.AppendLine("    /// Also handles shorthand: Experience.IndexProps -> Components.Experience.Index");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private static Type? InferComponentType(string propsTypeName)");
        sb.AppendLine("    {");
        sb.AppendLine("        // First, try to resolve the type as-is (might be fully qualified)");
        sb.AppendLine("        var propsType = Type.GetType(propsTypeName);");
        sb.AppendLine("        if (propsType != null)");
        sb.AppendLine("        {");
        sb.AppendLine("            propsTypeName = propsType.FullName ?? propsTypeName;");
        sb.AppendLine("        }");
        sb.AppendLine("        else");
        sb.AppendLine("        {");
        sb.AppendLine("            // Try with Templates.Generated prefix");
        sb.AppendLine("            propsType = Type.GetType($\"Templates.Generated.{propsTypeName}\");");
        sb.AppendLine("            if (propsType != null)");
        sb.AppendLine("            {");
        sb.AppendLine("                propsTypeName = propsType.FullName ?? propsTypeName;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        // Try to find the component type by namespace and name pattern");
        sb.AppendLine("        var parts = propsTypeName.Split('.');");
        sb.AppendLine("        ");
        sb.AppendLine("        // Look for Components namespace");
        sb.AppendLine("        var componentsIndex = -1;");
        sb.AppendLine("        for (int i = 0; i < parts.Length; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (parts[i].Equals(\"Components\", StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine("            {");
        sb.AppendLine("                componentsIndex = i;");
        sb.AppendLine("                break;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        // If no Components namespace found, try to infer from shorthand");
        sb.AppendLine("        // Pattern: Experience.IndexProps -> Components.Experience.Index");
        sb.AppendLine("        if (componentsIndex < 0 && parts.Length >= 2)");
        sb.AppendLine("        {");
        sb.AppendLine("            // Assume first part is category, second part contains component name");
        sb.AppendLine("            var category = parts[0];");
        sb.AppendLine("            ");
        sb.AppendLine("            // Try: Templates.Generated.Components.{Category}.Index");
        sb.AppendLine("            var componentTypeName = $\"Templates.Generated.Components.{category}.Index\";");
        sb.AppendLine("            var componentType = Type.GetType(componentTypeName);");
        sb.AppendLine("            if (componentType != null) return componentType;");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        if (componentsIndex < 0) return null;");
        sb.AppendLine("        ");
        sb.AppendLine("        // Build component type name: Components.{Category}.{Component}.Index");
        sb.AppendLine("        // Remove the last part (usually InputProps or Props) and add Index");
        sb.AppendLine("        var componentParts = new List<string>();");
        sb.AppendLine("        for (int i = 0; i < parts.Length - 1; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            componentParts.Add(parts[i]);");
        sb.AppendLine("        }");
        sb.AppendLine("        componentParts.Add(\"Index\");");
        sb.AppendLine("        ");
        sb.AppendLine("        var fullComponentTypeName = string.Join(\".\", componentParts);");
        sb.AppendLine("        ");
        sb.AppendLine("        // Try to find the type");
        sb.AppendLine("        var resolvedComponentType = Type.GetType(fullComponentTypeName);");
        sb.AppendLine("        if (resolvedComponentType != null) return resolvedComponentType;");
        sb.AppendLine("        ");
        sb.AppendLine("        // Try with Templates.Generated prefix");
        sb.AppendLine("        fullComponentTypeName = \"Templates.Generated.\" + fullComponentTypeName;");
        sb.AppendLine("        resolvedComponentType = Type.GetType(fullComponentTypeName);");
        sb.AppendLine("        ");
        sb.AppendLine("        return resolvedComponentType;");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Creates a props object from front matter dictionary and markdown body.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private static TProps CreatePropsFromFrontMatter<TProps>(Dictionary<string, object> frontMatter, string markdownBody) where TProps : class");
        sb.AppendLine("    {");
        sb.AppendLine("        // Use Activator.CreateInstance to bypass required property checks");
        sb.AppendLine("        var props = Activator.CreateInstance<TProps>();");
        sb.AppendLine("        if (props == null) throw new InvalidOperationException($\"Failed to create instance of {typeof(TProps).Name}\");");
        sb.AppendLine("        var propsType = typeof(TProps);");
        sb.AppendLine("        ");
        sb.AppendLine("        // Map front matter fields to props properties");
        sb.AppendLine("        foreach (var prop in propsType.GetProperties())");
        sb.AppendLine("        {");
        sb.AppendLine("            // Try to find matching front matter key (case-insensitive)");
        sb.AppendLine("            var key = frontMatter.Keys.FirstOrDefault(k => ");
        sb.AppendLine("                k.Equals(prop.Name, StringComparison.OrdinalIgnoreCase) ||");
        sb.AppendLine("                k.Equals(ToCamelCase(prop.Name), StringComparison.OrdinalIgnoreCase));");
        sb.AppendLine("            ");
        sb.AppendLine("            if (key != null && frontMatter.TryGetValue(key, out var value))");
        sb.AppendLine("            {");
        sb.AppendLine("                // Convert value to property type");
        sb.AppendLine("                var convertedValue = ConvertValue(value, prop.PropertyType);");
        sb.AppendLine("                if (convertedValue != null)");
        sb.AppendLine("                {");
        sb.AppendLine("                    prop.SetValue(props, convertedValue);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        // Special handling for DetailsMarkdown or similar fields");
        sb.AppendLine("        var markdownProp = propsType.GetProperty(\"DetailsMarkdown\") ?? propsType.GetProperty(\"Markdown\") ?? propsType.GetProperty(\"Content\");");
        sb.AppendLine("        if (markdownProp != null && markdownProp.PropertyType == typeof(string))");
        sb.AppendLine("        {");
        sb.AppendLine("            markdownProp.SetValue(props, markdownBody);");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        return props;");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Converts a value to the target type.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private static object? ConvertValue(object value, Type targetType)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (value == null) return null;");
        sb.AppendLine("        ");
        sb.AppendLine("        var valueType = value.GetType();");
        sb.AppendLine("        ");
        sb.AppendLine("        // If types match, return as-is");
        sb.AppendLine("        if (targetType.IsAssignableFrom(valueType))");
        sb.AppendLine("        {");
        sb.AppendLine("            return value;");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        // Convert to string first");
        sb.AppendLine("        var stringValue = value.ToString();");
        sb.AppendLine("        if (stringValue == null) return null;");
        sb.AppendLine("        ");
        sb.AppendLine("        // Handle nullable types");
        sb.AppendLine("        var underlyingType = Nullable.GetUnderlyingType(targetType) ?? targetType;");
        sb.AppendLine("        ");
        sb.AppendLine("        // Try common conversions");
        sb.AppendLine("        if (underlyingType == typeof(string))");
        sb.AppendLine("        {");
        sb.AppendLine("            return stringValue;");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        if (underlyingType == typeof(int) && int.TryParse(stringValue, out var intVal))");
        sb.AppendLine("        {");
        sb.AppendLine("            return intVal;");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        if (underlyingType == typeof(bool) && bool.TryParse(stringValue, out var boolVal))");
        sb.AppendLine("        {");
        sb.AppendLine("            return boolVal;");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        if (underlyingType == typeof(DateTime) && DateTime.TryParse(stringValue, out var dateVal))");
        sb.AppendLine("        {");
        sb.AppendLine("            return dateVal;");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Converts PascalCase to camelCase.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private static string ToCamelCase(string input)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrEmpty(input) || char.IsLower(input[0]))");
        sb.AppendLine("        {");
        sb.AppendLine("            return input;");
        sb.AppendLine("        }");
        sb.AppendLine("        return char.ToLowerInvariant(input[0]) + input.Substring(1);");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Extracts YAML front matter from a Markdig document.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private static Dictionary<string, object>? ExtractFrontMatter(Markdig.Syntax.MarkdownDocument document)");
        sb.AppendLine("    {");
        sb.AppendLine("        var yamlBlock = document.Descendants<YamlFrontMatterBlock>().FirstOrDefault();");
        sb.AppendLine("        if (yamlBlock == null) return null;");
        sb.AppendLine("        ");
        sb.AppendLine("        var yamlLines = new StringBuilder();");
        sb.AppendLine("        foreach (var line in yamlBlock.Lines.Lines)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (line.Slice.Text != null)");
        sb.AppendLine("            {");
        sb.AppendLine("                yamlLines.AppendLine(line.Slice.ToString());");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        var yamlText = yamlLines.ToString();");
        sb.AppendLine("        return ParseYaml(yamlText);");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Extracts markdown body (everything after front matter).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private static string ExtractMarkdownBody(string markdownContent)");
        sb.AppendLine("    {");
        sb.AppendLine("        // Find the end of front matter (---)");
        sb.AppendLine("        var lines = markdownContent.Split(new[] { \"\\r\\n\", \"\\r\", \"\\n\" }, StringSplitOptions.None);");
        sb.AppendLine("        var startIndex = 0;");
        sb.AppendLine("        ");
        sb.AppendLine("        // Skip first ---");
        sb.AppendLine("        if (lines.Length > 0 && lines[0].Trim() == \"---\")");
        sb.AppendLine("        {");
        sb.AppendLine("            startIndex = 1;");
        sb.AppendLine("            // Find second ---");
        sb.AppendLine("            for (int i = 1; i < lines.Length; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (lines[i].Trim() == \"---\")");
        sb.AppendLine("                {");
        sb.AppendLine("                    startIndex = i + 1;");
        sb.AppendLine("                    break;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        // Join remaining lines");
        sb.AppendLine("        return string.Join(Environment.NewLine, lines.Skip(startIndex));");
        sb.AppendLine("    }");
        sb.AppendLine("    ");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Parses YAML text into a dictionary.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private static Dictionary<string, object>? ParseYaml(string? yamlText)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrWhiteSpace(yamlText)) return null;");
        sb.AppendLine("        ");
        sb.AppendLine("        var dict = new Dictionary<string, object>();");
        sb.AppendLine("        var yaml = new YamlStream();");
        sb.AppendLine("        yaml.Load(new StringReader(yamlText));");
        sb.AppendLine("        ");
        sb.AppendLine("        if (yaml.Documents.Count == 0) return dict;");
        sb.AppendLine("        ");
        sb.AppendLine("        var root = yaml.Documents[0].RootNode as YamlMappingNode;");
        sb.AppendLine("        if (root == null) return dict;");
        sb.AppendLine("        ");
        sb.AppendLine("        foreach (var entry in root.Children)");
        sb.AppendLine("        {");
        sb.AppendLine("            var key = ((YamlScalarNode)entry.Key).Value ?? string.Empty;");
        sb.AppendLine("            var value = entry.Value switch");
        sb.AppendLine("            {");
        sb.AppendLine("                YamlScalarNode s => s.Value ?? string.Empty,");
        sb.AppendLine("                _ => entry.Value.ToString() ?? string.Empty");
        sb.AppendLine("            };");
        sb.AppendLine("            dict[key] = value;");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        return dict;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

