<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- <InternalsVisibleTo>ChtmlCompiler.Tests</InternalsVisibleTo> -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.44.0" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Parser/src/Femur.Chtml.Parser.csproj" />
    <ProjectReference Include="../../Runtime/src/Femur.Chtml.Runtime.csproj" />
  </ItemGroup>

</Project>
