<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>Femur.Messaging.InMemory</PackageId>
    <Authors>Nicholas Quandt</Authors>
    <Company>Quandt</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <OutputType>Library</OutputType>
    <Description>In-memory transport for Femur.Messaging. Use for testing.</Description>
    <PackageTags>messaging;testing;inmemory;femur</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Femur.Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Femur.Messaging.Tests" />
  </ItemGroup>

</Project>
